AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Secrets Manager secret for RDS credentials

Parameters:
  DBUsername:
    Type: String
    Description: Username for the RDS database

Resources:
  DBPasswordsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: db-secret
      Description: "RDS DB credentials"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUsername}"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\\'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

