version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  cloudformation:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy SecretsManager Stack
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/secrets-template.yml \
              --stack-name secrets-stack \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides DBUsername=Admin
      - run:
          name: Wait for SecretsManager Stack Completion
          command: |
            aws cloudformation wait stack-create-complete --stack-name secrets-stack   
      - run:
          name: Deploy CloudFormation Stack
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/main-template.yml \
              --stack-name raisetech-stack \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides DBUsername=Admin MyIpAdress=133.32.183.11/32
      - run:
          name: Wait for CloudFormation Stack Completion
          command: |
            aws cloudformation wait stack-create-complete --stack-name raisetech-stack
      - run:
          name: Get EC2 Instance Public IP
          command: |
            mkdir -p tmp
            export EC2_PUBLIC_IP=$(aws cloudformation describe-stacks \
              --stack-name raisetech-stack \
              --query "Stacks[0].Outputs[?OutputKey=='EC2InstancePublicIP'].OutputValue" \
              --output text)
            echo "$EC2_PUBLIC_IP" > tmp/ec2_public_ip.txt
            cat tmp/ec2_public_ip.txt
      - persist_to_workspace:
          root: tmp
          paths:
            - ec2_public_ip.txt

  deploy:
    docker:
      - image: cimg/python:3.11
    environment:
      TARGET_HOST: ""
      SSH_KEY_PATH: ~/.ssh/id_rsa
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install Ansible & AWS Modules
          command: |
            pip install --upgrade pip
            pip install ansible  Boto3 botocore
            ansible-galaxy collection install amazon.aws
            ansible --version
      - run:
          name: Generate ansible.cfg
          command: |
            echo '[defaults]' > ansible/ansible.cfg
            echo 'collections_paths = /home/circleci/.pyenv/versions/3.11.12/lib/python3.11/site-packages/ansible_collections:/home/circleci/.ansible/collections' >> ansible/ansible.cfg
            cat ansible/ansible.cfg
      - attach_workspace:
          at: tmp
      - run:
          name: Load EC2 Public IP from workspace
          command: |
            export EC2_PUBLIC_IP=$(cat tmp/ec2_public_ip.txt)
            echo "export TARGET_HOST=$EC2_PUBLIC_IP" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Generate the Inventory File
          command: |
            echo "[web]" > ansible/hosts
            echo "${TARGET_HOST} ansible_user=ec2-user ansible_ssh_private_key_file=${SSH_KEY_PATH}" ansible_python_interpreter=/usr/local/bin/python3.8 >> ansible/hosts
            cat ansible/hosts
      - run:
          name: Save IP and Security Group ID to env
          command: |
            echo 'export MY_IP=$(curl -s https://checkip.amazonaws.com)' >> $BASH_ENV
            echo 'export MY_CIDR=${MY_IP}/32' >> $BASH_ENV
            echo 'export SG_ID=$(aws cloudformation describe-stacks \
              --stack-name raisetech-stack \
              --query "Stacks[0].Outputs[?OutputKey==\`SecurityGroupId\`].OutputValue" \
              --output text)' >> $BASH_ENV
      - run:
          name: Allow SSH access from CircleCI
          command: |
            source $BASH_ENV
            echo "Adding SSH rule for ${MY_CIDR} to ${SG_ID}"
            aws ec2 authorize-security-group-ingress \
              --group-id "${SG_ID}" \
              --protocol tcp \
              --port 22 \
              --cidr "${MY_CIDR}" || echo "SSH rule already exists or failed, skipping"
      - run:
          name: Add host to known_hosts 
          command: |
            echo "TARGET_HOST: ${TARGET_HOST}"
            mkdir -p ~/.ssh
            ssh-keyscan -H ${TARGET_HOST} >> ~/.ssh/known_hosts || echo "ssh-keyscan failed"
            cat ~/.ssh/known_hosts || echo "cat failed"
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i ansible/hosts ansible/playbook.yml
      - run:
          name: Revoke SSH access
          command: |
            source $BASH_ENV
            echo "Removing SSH rule for ${MY_CIDR} from ${SG_ID}"
            aws ec2 revoke-security-group-ingress \
              --group-id "${SG_ID}" \
              --protocol tcp \
              --port 22 \
              --cidr "${MY_CIDR}"

  test:
    docker:
      - image: cimg/python:3.11
    environment:
      TARGET_HOST: ""
      SSH_KEY_PATH: ~/.ssh/id_rsa
    steps:
      - checkout
      - aws-cli/setup 
      - run:
          name: Install Serverspec
          command: |
            sudo apt update
            sudo apt install -y ruby ruby-dev build-essential curl
            echo 'export GEM_HOME="$HOME/.gem"' >> $BASH_ENV
            echo 'export PATH="$HOME/.gem/bin:$PATH"' >> $BASH_ENV
            echo "TARGET_HOST=${EC2_PUBLIC_IP}" >> $BASH_ENV
            source $BASH_ENV
            gem install serverspec rake
      - run:
          name: "Get CloudFormation Outputs & Secrets"
          command: |
            export RDS_ENDPOINT=$(aws cloudformation describe-stacks \
              --stack-name raisetech-stack \
              --query "Stacks[0].Outputs[?OutputKey=='DBEndpoint'].OutputValue" \
              --output text)
            export ALB_DNS=$(aws cloudformation describe-stacks \
              --stack-name raisetech-stack \
              --query "Stacks[0].Outputs[?OutputKey=='AlbDnsName'].OutputValue" \
              --output text)
            secret_json=$(aws secretsmanager get-secret-value \
              --secret-id db-secret \
              --region ap-northeast-1 \
              --query 'SecretString' \
              --output text)
            export DB_USERNAME=$(echo $secret_json | jq -r '.username')
            export DB_PASSWORD=$(echo $secret_json | jq -r '.password')
            echo "export RDS_ENDPOINT=$RDS_ENDPOINT" >> $BASH_ENV
            echo "export ALB_DNS=$ALB_DNS" >> $BASH_ENV
            echo "export DB_USERNAME=$DB_USERNAME" >> $BASH_ENV
            echo "export DB_PASSWORD=$DB_PASSWORD" >> $BASH_ENV
            source $BASH_ENV
      - attach_workspace:
          at: tmp
      - run:
          name: Load EC2 Public IP from workspace
          command: |
            export EC2_PUBLIC_IP=$(cat tmp/ec2_public_ip.txt)
            echo "export TARGET_HOST=$EC2_PUBLIC_IP" >> $BASH_ENV
            source $BASH_ENV 
      - run:
          name: Save IP and Security Group ID to env
          command: |
            echo "export MY_IP=$(curl -s https://checkip.amazonaws.com)" >> $BASH_ENV
            echo "export MY_CIDR=${MY_IP}/32" >> $BASH_ENV
            echo "export SG_ID=$(aws cloudformation describe-stacks \
              --stack-name raisetech-stack \
              --query "Stacks[0].Outputs[?OutputKey==\`SecurityGroupId\`].OutputValue" \
              --output text)' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Allow SSH access from CircleCI
          command: |
            echo "Adding SSH rule for ${MY_CIDR} to ${SG_ID}"
            aws ec2 authorize-security-group-ingress \
              --group-id "${SG_ID}" \
              --protocol tcp \
              --port 22 \
              --cidr "${MY_CIDR}" || echo "SSH rule already exists or failed, skipping" 
      - run:
          name: Run ServerSpec Tests
          command: |
            cd serverspec
            rake spec
      - run:
          name: Revoke SSH access
          command: |
            source $BASH_ENV
            echo "Removing SSH rule for ${MY_CIDR} from ${SG_ID}"
            aws ec2 revoke-security-group-ingress \
              --group-id "${SG_ID}" \
              --protocol tcp \
              --port 22 \
              --cidr "${MY_CIDR}"

workflows:
  version: 2
  raisetech:
    jobs:
#      - cfn-lint
      - cloudformation
#         requires:
#            - cfn-lint
#      - deploy:
#          requires:
#            - cloudformation
      - test:
#          requires:
#            - deploy

