version: 2.1

orbs:
  python: circleci/python@2.0.3
Parameters:
  target_host:
    type: string
    default: "13.231.228.188"

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  deploy:
    docker:
      - image: cimg/python:3.11
    environment:
      TARGET_HOST: << pipeline.parameters.target_host >>
      SSH_KEY_PATH: /home/circleci/.ssh/id_rsa
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install -y ansible

      - run:
          name: Generate Ansible inventory
          command: |
            echo "[web]" > ansible/hosts
            echo "${TARGET_HOST} ansible_user=ec2-user ansible_ssh_private_key_file=${SSH_KEY_PATH}" >> ansible/hosts

      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i ansible/hosts ansible/playbook.yml

  test:
    docker:
      - image: cimg/python:3.11
    environment:
      TARGET_HOST: << pipeline.parameters.target_host >>
      SSH_KEY_PATH: /home/circleci/.ssh/id_rsa
    steps:
      - checkout
      - run:
          name: Install Serverspec
          command: |
            sudo apt update
            sudo apt install -y ruby ruby-dev build-essential curl
            echo 'export GEM_HOME="$HOME/.gem"' >> $BASH_ENV
            echo 'export PATH="$HOME/.gem/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            gem install serverspec rake

      - run:
          name: Run ServerSpec Tests
          command: |
            cd serverspec
            rake spec

workflows:
  version: 2
  jobs:
    - cfn-lint
    - deploy
        requires:
          - cfn-lint
    - test
        requires:
          - deploy

