version: 2.1

orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  cloudformation:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy SecretsManager Stack
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/secrets-template.yml \
              --stack-name secrets-stack \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides DBUsername=Admin
      - run:
          name: Wait for SecretsManager Stack Completion
          command: |
            aws cloudformation wait stack-create-complete --stack-name secrets-stack
    
      - run:
          name: Deploy CloudFormation Stack
          command: |
            MY_IP=$(curl -s https://checkip.amazonaws.com)
            aws cloudformation deploy \
              --template-file cloudformation/main-template.yml \
              --stack-name raisetech-stack \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides DBUsername=Admin MyIpAdress=${MY_IP}/32
      - run:
          name: Wait for CloudFormation Stack Completion
          command: |
            aws cloudformation wait stack-create-complete --stack-name raisetech-stack
      - run:
          name: Get EC2 Instance Public IP
          command: |
            mkdir -p tmp
            export EC2_PUBLIC_IP=$(aws cloudformation describe-stacks \
              --stack-name raisetech-stack \
              --query "Stacks[0].Outputs[?OutputKey=='EC2InstancePublicIP'].OutputValue" \
              --output text)
            echo "$EC2_PUBLIC_IP" > tmp/ec2_public_ip.txt
            cat tmp/ec2_public_ip.txt
      - persist_to_workspace:
          root: tmp
          paths:
            - ec2_public_ip.txt

  deploy:
    docker:
      - image: cimg/python:3.11
    environment:
      TARGET_HOST: ""
      SSH_KEY_PATH: ~/.ssh/id_rsa
    steps:
      - checkout
      - run:
          name: Install Ansible & AWS Modules
          command: |
            pip install --upgrade pip
            pip install ansible  Boto3 botocore
            ansible-galaxy collection install amazon.aws:>=5.0.0 community.aws:>=5.0.
      - run:
          name: Generate ansible.cfg
          command: |
            echo '[defaults]' > ansible/ansible.cfg
            echo 'collections_paths = /home/circleci/.pyenv/versions/3.11.12/lib/python3.11/site-packages/ansible_collections:/home/circleci/.ansible/collections' >> ansible/ansible.cfg
            cat ansible/ansible.cfg
      - attach_workspace:
          at: tmp
      - run:
          name: Load EC2 Public IP from workspace
          command: |
            export EC2_PUBLIC_IP=$(cat tmp/ec2_public_ip.txt)
            echo "export TARGET_HOST=$EC2_PUBLIC_IP" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Generate the Inventory File
          command: |
            echo "[web]" > ansible/hosts
            echo "${TARGET_HOST} ansible_user=ec2-user ansible_ssh_private_key_file=${SSH_KEY_PATH}" ansible_python_interpreter=/usr/bin/python3.8>> ansible/hosts
            cat ansible/hosts
      - run:
          name: Add host to known_hosts 
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ${TARGET_HOST} >> ~/.ssh/known_hosts
            cat ~/.ssh/known_hosts
      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook -i ansible/hosts ansible/playbook.yml

  test:
    docker:
      - image: cimg/python:3.11
    environment:
      TARGET_HOST: ""
      SSH_KEY_PATH: ~/.ssh/id_rsa
    steps:
      - checkout
      - run:
          name: Install Serverspec
          command: |
            sudo apt update
            sudo apt install -y ruby ruby-dev build-essential curl
            echo 'export GEM_HOME="$HOME/.gem"' >> $BASH_ENV
            echo 'export PATH="$HOME/.gem/bin:$PATH"' >> $BASH_ENV
            echo "TARGET_HOST=${EC2_PUBLIC_IP}" >> $BASH_ENV
            source $BASH_ENV
            gem install serverspec rake
      - run:
          name: Run ServerSpec Tests
          command: |
            cd serverspec
            rake spec

workflows:
  version: 2
  raisetech:
    jobs:
      - cfn-lint
      - cloudformation:
          requires:
            - cfn-lint
      - deploy:
          requires:
            - cloudformation
      - test:
          requires:
            - deploy

