---
# 必要なパッケージ・環境のインストール
- import_tasks: setup.yml

# Railsアプリのクローンと依存インストール
- import_tasks: deploy.yml

# Nginxのインストール、設定
- import_tasks: nginx.yml

# Pumaサービスの設定
- import_tasks: puma.yml

# S3の設定
- import_tasks: s3.yml
